defaults:
  - ppo_trainer
  - _self_

algorithm:
  adv_estimator: grpo
  use_kl_in_reward: false
  kl_ctrl:
    type: fixed
    kl_coef: 0.001

data:
  train_files: /dfs/data/work/hardtry/data/train.parquet
  val_files: /dfs/data/work/hardtry/data/test.parquet
  train_batch_size: 64
  val_batch_size: 64
  max_prompt_length: 9216
  max_response_length: 1024
  truncation: 'left'
  return_raw_chat: true
  filter_overlong_prompts: false

actor_rollout_ref:
  num_workers: 4  # N_GPUS
  model_sharing: true
  load_on_worker: false
  model:
    path: /dfs/data/models/Qwen3-4B-Instruct-2507
    use_remove_padding: true
    trust_remote_code: true
    enable_gradient_checkpointing: true
  actor:
    ppo_mini_batch_size: 32
    ppo_micro_batch_size_per_gpu: 1
    use_kl_loss: true
    optim:
      lr: 1e-6
      weight_decay: 1e-4
    fsdp_config:
      optimizer_offload: true
      param_offload: false
    clip_ratio_low: 0.20
    clip_ratio_high: 0.28
    kl_loss_coef: 0.001
    entropy_coeff: 0
    kl_loss_type: low_var_kl
    strategy: fsdp
  ref:
    log_prob_micro_batch_size_per_gpu: 1
    strategy: fsdp
    fsdp_config:
      optimizer_offload: true
      param_offload: false
  rollout:
    name: vllm
    n: 4
    gpu_memory_utilization: 0.6
    tensor_model_parallel_size: 1
    log_prob_micro_batch_size_per_gpu: 1
    dtype: bfloat16

trainer:
  project_name: hardtry
  experiment_name: verl1
  n_gpus_per_node: 4  # N_GPUS
  nnodes: 1
  logger: ['console', 'swanlab']
  default_local_dir: /dfs/data/work/hardtry/checkpoints/verl1
  critic_warmup: 0.01
  save_freq: 50
  test_freq: 50
  val_before_train: true
  total_epochs: 1
  resume_mode: auto

custom_reward_function:
  path: /dfs/data/work/hardtry/exps/verl1/reward_fn.py
  name: compute_score

ray_init_kwargs:
  runtime_env:
    env_vars:
      RAY_memory_usage_threshold: 0.85
      RAY_memory_monitor_refresh_ms: 5000
      TOKENIZERS_PARALLELISM: "false"
      NCCL_DEBUG: "WARN"
      VLLM_LOGGING_LEVEL: "ERROR"
      VLLM_ALLOW_RUNTIME_LORA_UPDATING: "true"
      VLLM_ALLREDUCE_USE_SYMM_MEM: "0"
      CUDA_DEVICE_MAX_CONNECTIONS: "8"
      NCCL_CUMEM_ENABLE: "1"
  working_dir: /dfs/data/work/hardtry

hydra:
  searchpath:
    - file:///dfs/data/work/verl/verl/trainer/config/