defaults:
  - grpo_config
  - _self_

actor_rollout_ref:
  model:
    lora_rank: 16
    lora_alpha: 32
    target_modules: all-linear

trainer:
  experiment_name: verl2
  default_local_dir: /dfs/data/work/hardtry/checkpoints/verl2

hydra:
  searchpath:
    - file:///dfs/data/work/hardtry/exps/verl1/configs/