model_name: "Qwen/Qwen3-4B-FC"
test_category: "multi_turn_base"

base_artifact_dir: "/dfs/data/work/hardtry/eval_results"
experiment_name: "verl7_parallel_5runs"
summary_output_dir: "/dfs/data/work/hardtry/exps/verl7/eval5_results"

venv_activate_path: "/dfs/data/uv-venv/gorilla/bin/activate"
remote_openai_tokenizer_path: "/dfs/data/models/Qwen3-4B-Instruct-2507"

num_runs: 5
threads_per_run: 32

remote_openai_base_url: "http://localhost:8000/v1"
remote_openai_api_key: "EMPTY"
