# 模型基础路径
model: "/dfs/data/models/sloop-4b_dora1"
served_model_name: "sloop-4b"

# 基础设置
trust_remote_code: true
host: "0.0.0.0"
port: 8000

# 性能与显存
max_model_len: 65536
gpu_memory_utilization: 0.6
swap_space: 16

# 工具调用设置
enable_auto_tool_choice: true
tool_call_parser: "hermes"
